// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP5Ab6YrI3TukSZW-9B0yQuvHlFx-vQ5A',
    appId: '1:53380064447:web:c3e008348a83a28ba4d20a',
    messagingSenderId: '53380064447',
    projectId: 'portfolio-80ec4',
    authDomain: 'portfolio-80ec4.firebaseapp.com',
    storageBucket: 'portfolio-80ec4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIk6Q33_V24-QPp2E0wRT59psWf0w8QhA',
    appId: '1:53380064447:android:02c35c3729ef16cfa4d20a',
    messagingSenderId: '53380064447',
    projectId: 'portfolio-80ec4',
    storageBucket: 'portfolio-80ec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVtokbw6WTmM_QRNb_WXFu5XkfzfYfywU',
    appId: '1:53380064447:ios:1ac5ba7937f55006a4d20a',
    messagingSenderId: '53380064447',
    projectId: 'portfolio-80ec4',
    storageBucket: 'portfolio-80ec4.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVtokbw6WTmM_QRNb_WXFu5XkfzfYfywU',
    appId: '1:53380064447:ios:1ac5ba7937f55006a4d20a',
    messagingSenderId: '53380064447',
    projectId: 'portfolio-80ec4',
    storageBucket: 'portfolio-80ec4.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP5Ab6YrI3TukSZW-9B0yQuvHlFx-vQ5A',
    appId: '1:53380064447:web:9d8a4cabffb69667a4d20a',
    messagingSenderId: '53380064447',
    projectId: 'portfolio-80ec4',
    authDomain: 'portfolio-80ec4.firebaseapp.com',
    storageBucket: 'portfolio-80ec4.firebasestorage.app',
  );

}